apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.letsencrypt.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.letsencrypt.acme.email }}
    server: {{ .Values.clusterIssuer.letsencrypt.acme.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.letsencrypt.acme.privateKeySecretRefName }}
    solvers:
  {{- with .Values.clusterIssuer.letsencrypt.solvers}}
  {{- toYaml . | nindent 6}}
  {{- end}}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.privateCa.chaos.name }}
spec:
  ca:
    secretName: {{ .Values.clusterIssuer.privateCa.chaos.ca.secretName}}
